### PR TITLE
Refactor codebase for clarity, portability, and consistency improvements.

### PR DESCRIPTION
**Pull request by stevewgr**
### Description

This pull request introduces a series of codebase improvements to enhance clarity, portability, and maintainability. Key changes include namespace renaming, function refactoring, unused code removal, and consistency adjustments.

### Details
- **Namespace Renaming**: Renamed the `N3` namespace to `n3std` to emphasize its role as a utility namespace for standardizing the codebase, akin to the `std` namespace.
  
- **Function Refactoring**: Refactored and relocated `GetProgPath` and `LogFileWrite` to `N3Utils.h`. This centralization reduces code duplication and ensures compatibility across all platforms.

- **Redundant Code Removal**: Removed unused and redundant code from the Launcher, which included a custom button control that was never used. Additionally, removed an unused Windows-based `ShellTree` implementation to streamline the codebase.

- **Improved Dialog Functionality**: Replaced the custom `DlgBrowsePath` dialog with `CFolderPickerDialog`. The previous implementation had limitations with deeply nested folders and lacked path copy-paste functionality. Using `CFolderPickerDialog` offers a modern, user-friendly folder selection approach, leveraging Windows Explorer’s capabilities.

- **Memory Allocation Warning Fix**: Fixed warnings associated with large stack buffers by replacing `char buff[size]` with `std::vector<char>`. This change enables dynamic memory allocation for large buffers, specifically in multi-file selection dialogs, using a 512 KB buffer to support long file paths.

- **Consistent Header Includes**: Standardized header includes to improve portability and consistency. This involved addressing inconsistent casing and correcting system headers to use angle brackets (`<>`) instead of quotes (`""`). Future enhancements may involve integrating tools like clang-tidy or include-what-you-use (iwyu) for further consistency.

### Benefits
These updates enhance the overall quality of the codebase by improving portability, reducing redundancy, ensuring compatibility, and simplifying functionality. They lay the groundwork for a more standardized, maintainable, and user-friendly application.

### CODE REVIEW

**Comment by stevewgr** [comment]
Build passing: https://github.com/ko4life-net/ko/actions/runs/11790164397/job/32840149101

Also worth mentioning that build time almost reduced by 2 minutes 🤯 🎉 🚀

**Comment by SeniourMarquies** [comment]
You're an antworker.

**Review by UTengine — APPROVED** [review]
Ok

**Review by UTengine — APPROVED** [review]
Ok

**Review by UTengine — APPROVED** [review]
Ok

**Review by UTengine — APPROVED** [review]
Ok

**Review by UTengine — APPROVED** [review]
Fine

**Comment by stevewgr** [comment]
Build passing: https://github.com/ko4life-net/ko/actions/runs/11807325401

Merging.

**Review by srmeier — APPROVED** [review]

**Pull request merged**
