### PR TITLE
WIP: 1264 UIs.

### PR DESCRIPTION
**Pull request by stevewgr**
### Description

Note that we'll merge this for now, even though it's not cleaned up yet, just because there is a lot of work to do on UIs that it will be easier to to manage that way.

We'll fix and implement UI logic as we go.

### CODE REVIEW

**Comment by stevewgr** [comment]
Test discord integration

**Comment by stevewgr** [comment]
Test discord integration

**Comment by stevewgr** [comment]
Test discord integration

**Review by xGuTeK — APPROVED** [review]
Everything is fine ;)

**Pull request merged**
