### PR TITLE
Bump db version from 1.0.0 to 1.0.2.

### PR DESCRIPTION
**Pull request by stevewgr**
### Description

Bump db version from 1.0.0 to 1.0.2.

Resolves the following issue: https://github.com/ko4life-net/ko/issues/223

### CODE REVIEW

**Comment by stevewgr** [comment]
@twostars works on your end?

**Comment by twostars** [comment]
@stevewgr I still get a couple that you seem to have missed:
```
C:\Users\twostars\Desktop\ko\src\db\src\procedure\EDITER_KNIGHTS.sql
Invoke-Sqlcmd : Must declare the scalar variable "@Row".
 Msg 137, Level 15, State 2, Procedure EDITER_KNIGHTS, Line 25.
```

```
C:\Users\twostars\Desktop\ko\src\db\src\procedure\RANK_KNIGHTS.sql
Invoke-Sqlcmd : Must declare the scalar variable "@Knightsindex".
Must declare the scalar variable "@knightsindex".
 Msg 137, Level 15, State 2, Procedure RANK_KNIGHTS, Line 20.
```

The rest are fine now though.

**Comment by stevewgr** [comment]
@twostars no idea how I missed that lol
probably missed it during staging files, but I made an annoying rebase since it was tagged release and considering there is not much activity in the repo, I forced pushed it as an exception.
Could you please try again?

**Comment by twostars** [comment]
All fixed now

**Pull request merged**
