### PR TITLE
Transcode and normalize encoding of all files across the project

### PR DESCRIPTION
**Pull request by stevewgr**
### Description

Resolves the following issue: https://github.com/ko4life-net/ko/issues/240

This PR introduces the following changes:
- Standardized and normalized file encoding across the project by transcoding all text-based files to UTF-8. This ensures compatibility with modern systems and supports multiple languages, specifically Korean, Chinese, and Polish characters. Microsoft's resource files (`*.rc`) are exempt and transcoded to UTF-16 Little Endian (LE byte order) with a Byte Order Marker (BOM).

- Converted all Windows CRLF line endings to Unix LF to ensure cross-platform compatibility and consistency in various editors.

- Implemented a python script to automate the encoding standardization and line ending conversion.

- Configured `.gitattributes` to handle `*.rc` files as text with UTF-16 encoding, preventing them from being misinterpreted as binary and ensuring proper diff display.

- Added a `.editorconfig` file to enforce encoding consistency for future files and modifications.

### Workflow

```powershell
# 1.
git clone git@github.com:ko4life-net/ko.git

# 2. Run detect encoding to generate the csv files.
python .\ko\script\fix-encoding.py --root-dir .\ko --detect-encoding

# 3. Update and review the guessed encoding in ko-encoding-manual.csv file to match with the correct source encoding.
# Also merge whatever you found faulty in ko-encoding-invalid.csv into ko-encoding-manual.csv as needed.

# 4. Run ko-encoding-manual.csv -> check yourself -> all good? run the main ko-encoding.csv file
python .\ko\script\fix-encoding.py --encoding-file .\ko-encoding-manual.csv
python .\ko\script\fix-encoding.py --encoding-file .\ko-encoding.csv

# 5. Final touch: convert all files to use Unix LF line feed instead Windows CRLF
python .\ko\script\fix-encoding.py --root-dir .\ko --crlf-to-lf

# 6. Run format.ps1
```

### Results

- [ko-encoding-manual.csv](https://github.com/user-attachments/files/16322348/ko-encoding-manual.csv)

- [ko-encoding.csv](https://github.com/user-attachments/files/16322347/ko-encoding.csv)

### Log files

- [1_fix-encoding_detection_2024-07-20_15-24-47.log](https://github.com/user-attachments/files/16322349/1_fix-encoding_detection_2024-07-20_15-24-47.log)
- [2_fix-encoding_transcode_manual_2024-07-20_15-29-42.log](https://github.com/user-attachments/files/16322350/2_fix-encoding_transcode_manual_2024-07-20_15-29-42.log)
- [3_fix-encoding_transcode_2024-07-20_15-34-25.log](https://github.com/user-attachments/files/16322351/3_fix-encoding_transcode_2024-07-20_15-34-25.log)
- [4_fix-encoding_crlf_to_lf_2024-07-20_15-38-48.log](https://github.com/user-attachments/files/16322352/4_fix-encoding_crlf_to_lf_2024-07-20_15-38-48.log)

### CODE REVIEW

**Comment by xGuTeK** [comment]
1. I cloned the repository and switched the branch to fix-encoding.
   2. I installed the missing Python modules magic and chardet.
   3. I opened the project in Visual Studio and saw strange symbols instead of Korean characters, then I closed VS.
   4. I ran all the commands from the workflow.
   5. I reopened the project and noticed that now there are Korean characters.
   6. I made a few changes to the files, saved, and reopened VS, and I still see the Korean characters.

So everything works.

**Review by xGuTeK — APPROVED** [review]
I cloned the repository and switched the branch to fix-encoding.
    I installed the missing Python modules magic and chardet.
    I opened the project in Visual Studio and saw strange symbols instead of Korean characters, then I closed Visual Studio.
    I ran all the commands from the workflow.
    I reopened the project and noticed that now there are Korean characters.
    I made a few changes to the files, saved, and reopened VS, and I still see the Korean characters.

So everything works.

**Review by srmeier — APPROVED** [review]

**Comment by twostars** [comment]
> ```
> I cloned the repository and switched the branch to fix-encoding.
> I installed the missing Python modules magic and chardet.
> I opened the project in Visual Studio and saw strange symbols instead of Korean characters, then I closed Visual Studio.
> I ran all the commands from the workflow.
> I reopened the project and noticed that now there are Korean characters.
> I made a few changes to the files, saved, and reopened VS, and I still see the Korean characters.
> ```
> 
> So everything works.

```
f:\git\ko-encoding>git checkout fix-encoding
error: failed to encode 'src/game/res/Resource.rc' from UTF-8 to UTF-16
error: failed to encode 'src/server/AIServer/res/AIServer.rc' from UTF-8 to UTF-16
error: failed to encode 'src/server/AIServer/res/AIServer.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/server/Aujard/Aujard.rc' from UTF-8 to UTF-16
error: failed to encode 'src/server/Aujard/res/Aujard.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/server/Ebenezer/Ebenezer.rc' from UTF-8 to UTF-16
error: failed to encode 'src/server/Ebenezer/res/Ebenezer.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/server/ItemManager/ItemManager.rc' from UTF-8 to UTF-16
error: failed to encode 'src/server/ItemManager/res/ItemManager.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/server/LoginServer/LoginServer.rc' from UTF-8 to UTF-16
error: failed to encode 'src/server/LoginServer/res/LoginServer.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/KscViewer/KscViewer.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/KscViewer/res/KscViewer.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/Launcher/Launcher/Launcher.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/Launcher/Launcher/res/Launcher.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/N3CE/N3CE.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/N3CE/res/N3CE.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/N3FXE/N3FXE.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/N3FXE/res/N3FXE.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/N3Indoor/N3Indoor.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/N3Indoor/res/N3Indoor.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/N3ME/N3ME.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/N3ME/res/N3ME.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/N3TexViewer/N3TexViewer.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/N3TexViewer/res/N3TexViewer.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/N3Viewer/N3Viewer.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/N3Viewer/res/N3Viewer.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/Option/Option.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/Option/res/Option.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/PlugIn_Max/N3DExp.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/PlugIn_Maya/Resource.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/RscTables/RscTables.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/RscTables/res/RscTables.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/ServerInfoViewer/ServerInfoViewer.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/ServerInfoViewer/res/ServerInfoViewer.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/SkyViewer/SkyViewer.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/SkyViewer/res/SkyViewer.rc2' from UTF-8 to UTF-16
error: failed to encode 'src/tool/UIE/UIE.rc' from UTF-8 to UTF-16
error: failed to encode 'src/tool/UIE/res/UIE.rc2' from UTF-8 to UTF-16
Switched to a new branch 'fix-encoding'
branch 'fix-encoding' set up to track 'origin/fix-encoding'.

f:\git\ko-encoding>
```

image

**Comment by stevewgr** [comment]
> > ```
> > I cloned the repository and switched the branch to fix-encoding.
> > I installed the missing Python modules magic and chardet.
> > I opened the project in Visual Studio and saw strange symbols instead of Korean characters, then I closed Visual Studio.
> > I ran all the commands from the workflow.
> > I reopened the project and noticed that now there are Korean characters.
> > I made a few changes to the files, saved, and reopened VS, and I still see the Korean characters.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So everything works.
> 
> ```
> f:\git\ko-encoding>git checkout fix-encoding
> error: failed to encode 'src/game/res/Resource.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/server/AIServer/res/AIServer.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/server/AIServer/res/AIServer.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/server/Aujard/Aujard.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/server/Aujard/res/Aujard.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/server/Ebenezer/Ebenezer.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/server/Ebenezer/res/Ebenezer.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/server/ItemManager/ItemManager.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/server/ItemManager/res/ItemManager.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/server/LoginServer/LoginServer.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/server/LoginServer/res/LoginServer.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/KscViewer/KscViewer.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/KscViewer/res/KscViewer.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/Launcher/Launcher/Launcher.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/Launcher/Launcher/res/Launcher.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/N3CE/N3CE.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/N3CE/res/N3CE.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/N3FXE/N3FXE.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/N3FXE/res/N3FXE.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/N3Indoor/N3Indoor.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/N3Indoor/res/N3Indoor.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/N3ME/N3ME.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/N3ME/res/N3ME.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/N3TexViewer/N3TexViewer.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/N3TexViewer/res/N3TexViewer.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/N3Viewer/N3Viewer.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/N3Viewer/res/N3Viewer.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/Option/Option.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/Option/res/Option.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/PlugIn_Max/N3DExp.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/PlugIn_Maya/Resource.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/RscTables/RscTables.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/RscTables/res/RscTables.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/ServerInfoViewer/ServerInfoViewer.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/ServerInfoViewer/res/ServerInfoViewer.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/SkyViewer/SkyViewer.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/SkyViewer/res/SkyViewer.rc2' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/UIE/UIE.rc' from UTF-8 to UTF-16
> error: failed to encode 'src/tool/UIE/res/UIE.rc2' from UTF-8 to UTF-16
> Switched to a new branch 'fix-encoding'
> branch 'fix-encoding' set up to track 'origin/fix-encoding'.
> 
> f:\git\ko-encoding>
> ```
> 
> image

Yep, I'm aware and it has nothing to do with the changes, specifically the rc encoding, rather `.gitattributes` that I'm testing with.
I might drop the `.gitatrributes` if it still acts up with UTF-16.

**Comment by twostars** [comment]
Seems someone's making assumptions because I just one again gave you evidence of a problem and you start going off. Never change my guy.

**Comment by twostars** [comment]
Ah, back to silencing because you're called out for your obnoxious behaviour. If you can't stand the heat, get out of the kitchen. Not like you're doing any real cooking anyway.

**Comment by stevewgr** [comment]
> Ah, back to silencing because you're called out for your obnoxious behaviour. If you can't stand the heat, get out of the kitchen. Not like you're doing any real cooking anyway.

No, because this is a pull-request and your comment content did not contribute anything to the discussion and rather insulting. Kolin made it clear on discord that you're doing this for business to get leads, so if you don't want to contribute to the project, then why bother.

**Comment by stevewgr** [comment]
I ran some investigation on why would the new `.gitattributes` configurations messes up in the wrong way, where it tries to take a perfectly fine UTF-16-LE encoded RC file and rencode it from UTF-8 to UTF-16. This seems like an unexpected behavior from gitattributes, and hence I removed these configs: https://github.com/ko4life-net/ko/pull/241/commits/317d79598a439dbac4c3eada2e59302c005320a2

I initially added them so that when I run from the terminal `git diff`, I'll be able to see the content, since git doesn't handle well with UTF-16 encoded files and treat them as binary instead of text.
However UI based diffing still works in vscode, GitHub and some others, so let's remove these configs from `.gitattributes` and merge this PR.

Also there are some work around in case someone still want to see the diff of UTF-16 encoded text files by changing the default diff tool: https://stackoverflow.com/questions/777949/can-i-make-git-recognize-a-utf-16-file-as-text

I tested the build on multiple scenarios and they seem to all pass perfectly fine:
- https://github.com/ko4life-net/ko/actions/runs/10025128918
- https://github.com/ko4life-net/ko/actions/runs/10025178930
- https://github.com/ko4life-net/ko/actions/runs/10025179949
- https://github.com/ko4life-net/ko/actions/runs/10025221456

Thanks for the review @xGuTeK and @srmeier 🚀

**Pull request merged**
